InvoiceManager/Models/Domains/Client.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InvoiceManager.Models.Domains
{
    public class Client
    {
        public Client()
        {
            Invoices = new Collection<Invoice>();
        }

        [Required]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public int AddressId { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        [ForeignKey(nameof(User))]
        public string UserId { get; set; }

        public Address Address { get; set; }
        public ICollection<Invoice> Invoices { get; set; }
        public ApplicationUser User { get; set; }
    }

    
}

InvoiceManager/Models/Domains/Invoice.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace InvoiceManager.Models.Domains
{
    public class Invoice
    {
        public Invoice()
        {
            InvoicePositions = new Collection<InvoicePosition>();
        }
        public int Id { get; set; }

        [Required(ErrorMessage ="Pole Tytuł jest wymagane")]
        [Display(Name = "Tytuł")]
        public string Title { get; set; }

        [Display(Name = "Wartość")]
        [Required(ErrorMessage = "Pole Wartość jest wymagane")]
        public decimal Value { get; set; }

        [Display(Name = "Sposób płatności")]
        [Required(ErrorMessage = "Pole Sposób płatności jest wymagane")]
        public int MethodOfPaymentId { get; set; }

        [Display(Name = "Termin płatności")]
        [Required(ErrorMessage = "Pole Termin płatności jest wymagane")]
        public DateTime PaymentDate { get; set; }

        [Display(Name = "Data utworzenia")]
        public DateTime CreatedDate { get; set; }


        [Display(Name = "Uwagi")]
        public string Comments { get; set; }


        [Display(Name = "Klient")]
        [Required(ErrorMessage = "Pole Klient jest wymagane")]
        public int ClientId { get; set; }
        [Required]
        [ForeignKey(nameof(User))]
        public string UserId { get; set; }


        public MethodOfPayment MethodOfPayment { get; set; }
        public Client Client { get; set; }
        public ApplicationUser User { get; set; }
        public ICollection<InvoicePosition> InvoicePositions { get; set; }

    }
}

InvoiceManager/Models/Domains/InvoicePosition.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace InvoiceManager.Models.Domains
{
    public class InvoicePosition
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Pole Lp jest wymagane")]
        public int Lp { get; set; }

        public int InvoiceId { get; set; }

        [Display(Name = "Wartość")]
        [Required(ErrorMessage = "Pole Wartość jest wymagane")]
        public decimal Value { get; set; }

        [Display(Name = "Produkt")]
        [Required(ErrorMessage = "Pole Produkt jest wymagane")]
        public int ProductId { get; set; }

        [Display(Name = "Ilość")]
        public int Quantity { get; set; }

        public Invoice Invoice { get; set; }
        public Product Product { get; set; }
    }
}

InvoiceManager/Controllers/HomeController.cs
using InvoiceManager.Models.Domains;
using InvoiceManager.Models.Repositories;
using InvoiceManager.Models.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InvoiceManager.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private InvoiceRepository _invoiceRepository = new InvoiceRepository();
        private ClientRepository _clientRepository = new ClientRepository();
        private ProductRepository _productRepository = new ProductRepository();

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Invoices()
        {
            var userId = User.Identity.GetUserId();

            var invoices = _invoiceRepository.GetInvoices(userId);
            return View(invoices);
        }



        public ActionResult Clients()
        {
            var userId = User.Identity.GetUserId();

            var clients = _clientRepository.GetClients(userId);

            return View(clients);
        }



        public ActionResult Invoice(int id = 0)
        {
            var userId = User.Identity.GetUserId();
            var invoice = id == 0 ?
                            GetNewInvoice(userId) :
                            _invoiceRepository.GetInvoice(id, userId);
            var vm = PrepareInvoiceVm(invoice, userId);

            return View(vm);
        }

        public ActionResult Client(int id = 0)
        {
            var userId = User.Identity.GetUserId();
            ViewBag.Heading = id == 0 ? "Dodawanie nowego klienta" : "Klient";
            var client = id == 0 ?
                            GetNewClient(userId) :
                            _clientRepository.GetClient(id, userId);
            return View(client);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Invoice(Invoice invoice)
        {
            var userId = User.Identity.GetUserId();
            invoice.UserId = userId;

            if (!ModelState.IsValid)
            {
                var vm = PrepareInvoiceVm(invoice, userId);
                return View("Invoice", vm);
            }

            if (invoice.Id == 0)
            {
                _invoiceRepository.Add(invoice);
            }
            else
            {
                _invoiceRepository.Update(invoice);
            };
            return RedirectToAction("Invoices");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Client(Client client)
        {
            var userId = User.Identity.GetUserId();
            client.UserId = userId;

            if (!ModelState.IsValid)
            {
                return View("Client", client);
            }


            if (client.Id == 0)
            {
                _clientRepository.Add(client);
            }
            else
            {
                _clientRepository.Update(client);
            }
            return RedirectToAction("Clients");
        }



        [HttpPost]
        public ActionResult Address(Address address)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { id = 0 });
            }

            int addressId = 0;

            if (address.Id == 0)
            {
                addressId = _clientRepository.AddAddress(address).Id;
            }

            return Json(new { id = addressId });
        }

        private EditInvoiceViewModel PrepareInvoiceVm(Invoice invoice, string userId)
        {
            return new EditInvoiceViewModel
            {
                Invoice = invoice,
                Heading = invoice.Id == 0 ? "Dodawanie nowej faktury" : "Faktura",
                Clients = _clientRepository.GetClients(userId),
                MethodsOfPayment = _invoiceRepository.GetMethodsOfPayment()
            };
        }



        private Invoice GetNewInvoice(string userId)
        {
            return new Invoice
            {
                UserId = userId,
                CreatedDate = DateTime.Now,
                PaymentDate = DateTime.Now.AddDays(7)
            };
        }

        private Client GetNewClient(string userId)
        {
            ViewBag.Heading = "Dodawanie nowego klienta";

            return new Client
            {
                UserId = userId
            };
        }

        public ActionResult InvoicePosition(int invoiceId, int invoicePositionId = 0)
        {
            var userId = User.Identity.GetUserId();

            var invoicePosition = invoicePositionId == 0 ?
                                    GetNewPosition(invoiceId) :
                                    _invoiceRepository.GetInvoicePosition(invoicePositionId, userId);

            var vm = PrepareInvoicePositionVm(invoicePosition);


            return View(vm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult InvoicePosition(InvoicePosition invoicePosition)
        {
            var userId = User.Identity.GetUserId();

            var product = _productRepository
                            .GetProduct(invoicePosition.ProductId);

            if (!ModelState.IsValid)
            {
                var vm = PrepareInvoicePositionVm(invoicePosition);
                return View("InvoicePosition", vm);
            }

            invoicePosition.Value = invoicePosition.Quantity * product.Value;

            if (invoicePosition.Id == 0)
            {
                _invoiceRepository.AddPosition(invoicePosition, userId);
            }
            else
            {
                _invoiceRepository.UpdatePosition(invoicePosition, userId);
            }

            _invoiceRepository.UpdateInvoiceValue(invoicePosition.InvoiceId, userId);

            return RedirectToAction("Invoice", new { id = invoicePosition.InvoiceId });
        }

        [HttpPost]
        public ActionResult DeleteInvoice(int id)
        {

            try
            {
                var userId = User.Identity.GetUserId();
                _invoiceRepository.Delete(id, userId);
            }
            catch (Exception ex)
            {
                //logowanie
                return Json(new { Success = false, Message = ex.Message });
            }


            return Json(new { Success = true });
        }

        [HttpPost]
        public ActionResult DeletePosition(int id, int invoiceId)
        {
            var invoiceValue = 0m;

            try
            {
                var userId = User.Identity.GetUserId();
                _invoiceRepository.DeletePosition(id, userId);
                invoiceValue = _invoiceRepository.UpdateInvoiceValue(invoiceId, userId);
            }
            catch (Exception ex)
            {
                //logowanie
                return Json(new { Success = false, Message = ex.Message });
            }


            return Json(new { Success = true, InvoiceValue = invoiceValue });
        }

        [HttpPost]
        public ActionResult DeleteClient(int id)
        {

            try
            {
                var userId = User.Identity.GetUserId();
                _clientRepository.Delete(id, userId);
            }
            catch (Exception ex)
            {
                //logowanie
                return Json(new { Success = false, Message = ex.Message });
            }


            return Json(new { Success = true });
        }

        private EditInvoicePositionViewModel PrepareInvoicePositionVm(InvoicePosition invoicePosition)
        {
            return new EditInvoicePositionViewModel
            {
                InvoicePosition = invoicePosition,
                Heading = invoicePosition.Id == 0 ? "Dodawanie nowej pozycji" : "Pozycja",
                Products = _productRepository.GetProducts()
            };
        }

        private InvoicePosition GetNewPosition(int invoiceId)
        {
            return new InvoicePosition
            {
                InvoiceId = invoiceId
            };
        }

        [AllowAnonymous]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";


            return View();
        }


        [AllowAnonymous]
        public ActionResult Contact()
        {

            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

InvoiceManager/Controllers/PrintController.cs
using InvoiceManager.Models.Domains;
using InvoiceManager.Models.Repositories;
using Microsoft.AspNet.Identity;
using Rotativa;
using Rotativa.Options;
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InvoiceManager.Controllers
{
    [Authorize]
    public class PrintController : Controller
    {
        private InvoiceRepository _invoiceRepository = new InvoiceRepository();
      
        public ActionResult InvoiceToPdf(int id)
        {
            var handle = Guid.NewGuid().ToString();
            var userId = User.Identity.GetUserId();
            var invoice = _invoiceRepository.GetInvoice(id, userId);

            TempData[handle] = GetPdfContent(invoice);

            return Json(new
            {
                FileGuid = handle,
                FileName = $@"Faktura_{invoice.Id}.pdf"
            });
        }

        private byte[] GetPdfContent(Invoice invoice)
        {
            var pdfResult = new ViewAsPdf(@"InvoiceTemplate", invoice)
            {
                PageSize = Size.A4,
                PageOrientation = Orientation.Portrait
            };
            return pdfResult.BuildFile(ControllerContext);
        }

        public ActionResult DownloadInvoicePdf(string fileGuid, string fileName)
        {
            if (TempData[fileGuid] == null)
                throw new Exception("Błąd przy próbie eksportu faktury do PDF.");

            var data = TempData[fileGuid] as byte[];
            return File(data, "application/pdf", fileName);
        }

  
        public ActionResult PrintInvoice(int invoiceId)
        {
            var userId = User.Identity.GetUserId();
            var invoice = _invoiceRepository.GetInvoice(invoiceId, userId);

            var pdfResult = new ViewAsPdf(@"InvoiceTemplate", invoice)
            {
                PageSize = Size.A4,
                PageOrientation = Orientation.Portrait
            };
            return pdfResult;
        }

     



    }
}

InvoiceManager/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

InvoiceManager/Views/Home/Client.cshtml
@using InvoiceManager.Models.Domains

@model Client

@{
    ViewBag.Title = ViewBag.Heading;
}

<h2 class="mb-3">@ViewBag.Heading</h2>


<div class="row">
    <div class="col-lg-6">
        @using (Html.BeginForm("Client", "Home", FormMethod.Post, new { id = "client-form" }))
        {
            @Html.AntiForgeryToken()

            if (Model.Id == 0)
            {
                <p class="alert alert-info mt-4 mb-4">
                    Pola nazwa, ulica, numer, kod pocztowy, miasto oraz email są <strong>wymagane</strong>
                </p>
            }

            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.UserId)
            if (Model.Id != 0)
            {
                @Html.HiddenFor(x => x.AddressId);
                @Html.HiddenFor(x => x.Address.Id);
            }
            

            <div class="form-group">
                @Html.LabelFor(x => x.Name)
                @Html.TextBoxFor(x => x.Name,
                    new
                         {
                             @class = "form-control",
                            autofocus = "autofocus"
                         })
                @Html.ValidationMessageFor(x => x.Name)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Address.Street)
                @Html.TextBoxFor(x => x.Address.Street,
                    new
                         {
                             @class = "form-control"
                         })
                @Html.ValidationMessageFor(x => x.Address.Street)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Address.Number)
                @Html.TextBoxFor(x => x.Address.Number,
                    new
                         {
                             @class = "form-control"
                         })
                @Html.ValidationMessageFor(x => x.Address.Number)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Address.City)
                @Html.TextBoxFor(x => x.Address.City,
                    new
                         {
                             @class = "form-control"
                         })
                @Html.ValidationMessageFor(x => x.Address.City)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Address.PostalCode)
                @Html.TextBoxFor(x => x.Address.PostalCode,
                    new
                         {
                             @class = "form-control"
                         })
                @Html.ValidationMessageFor(x => x.Address.PostalCode)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Email)
                @Html.TextBoxFor(x => x.Email,
                    new
                         {
                             @class = "form-control"
                         })
                @Html.ValidationMessageFor(x => x.Email)
            </div>

            <button class="btn btn-primary btn-lg mb-5" type="submit">
                Zapisz
            </button>

        }
    </div>

</div>

InvoiceManager/Views/Home/Clients.cshtml
@using InvoiceManager.Models.Domains

@model IEnumerable<Client>

@{
    ViewBag.Title = "Klienci";
}

<h2 class="mb-3">Klienci</h2>

<button class="btn btn-primary mb-3"
        onclick='window.location.href="@Url.Action("Client", "Home")"'>
    Dodaj
</button>



@if (Model != null && Model.Any())
{
    <table class="table table-hover table-stripped mt-3 mb-5">
        <thead>
            <tr>
                <th scope="col">Nazwa</th>
                <th scope="col">Adres</th>
                <th scope="col">Email</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var client in Model)
            {
                <tr>
                    <td>
                        <a class="fw-bold text-decoration-none"
                           href='@Url.Action("Client", "Home",
                                new {id=client.Id})'>
                            @client.Name
                        </a>
                    </td>
                    <td>@client.Address.Street @client.Address.Number, @client.Address.PostalCode, @client.Address.City</td>
                    <td> @client.Email</td>
                    <td>
                        <button class="btn btn-danger btn-sm"
                                onclick="deleteClient('@client.Id', this)">
                            Usuń
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div>Brak klientów do wyświetlenia</div>
}

@section Scripts
{
    <script type="text/javascript">
        function deleteClient(id, btn){
            if(!confirm("Czy na pewno chcesz usunąć klienta?"))
                return;

            $.ajax({
                type: 'POST',
                url: "@Url.Action("DeleteClient", "Home")",
                data: {
                    id: id
                },
                success: function (data) {
                    if (data.Success) {
                        var row = btn.parentNode.parentNode;
                        row.parentNode.removeChild(row);
                    } else {
                        alert(data.Message);
                    }
                },
                error: function (data) {
                    alert(data.Message);
                },
                dataType: 'json'
            });
        }
    </script>
}

InvoiceManager/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

InvoiceManager/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Strona główna";
}

<h1 class="mb-3">Strona główna</h1>

<button class="btn btn-primary mb-3"
        onclick='window.location.href="@Url.Action("Invoices", "Home")"'>
    Faktury
</button>

<button class="btn btn-primary mb-3"
        onclick='window.location.href="@Url.Action("Clients", "Home")"'>
    Klienci
</button>

InvoiceManager/Views/Home/Invoice.cshtml
@model InvoiceManager.Models.ViewModels.EditInvoiceViewModel

@{
    ViewBag.Title = @Model.Heading;
}

<h1 class="mb-3">@Model.Heading</h1>

@if (Model.Invoice.Id != 0)
{
    <button class="btn btn-primary mb-3"
            onclick='window.location.href="@Url.Action("InvoicePosition", "Home", new {invoiceId=Model.Invoice.Id})"'>
        Dodaj pozycję
    </button>
    <button class="btn btn-secondary mb-3" onclick="generatePdf()">Generuj PDF</button>
    <button class="btn btn-secondary mb-3" onclick='window.location.href="@Url.Action("PrintInvoice", "Print", new {invoiceId=Model.Invoice.Id})"'>Drukuj</button>
}
<div class="row">
    <div class="col-lg-6">
        @using (Html.BeginForm("Invoice", "Home"))
        {
            @Html.AntiForgeryToken()

            if (Model.Invoice.Id == 0)
            {
                <p class="alert alert-info mt-4 mb-4">
                    Pola tytuł, klient, sposób płatności i termin są <strong>wymagane</strong>
                </p>
            }

            @Html.HiddenFor(x => x.Invoice.Id)
            @Html.HiddenFor(x => x.Invoice.UserId)

            <div class="form-group">
                @Html.LabelFor(x => x.Invoice.Title)
                @Html.TextBoxFor(x => x.Invoice.Title,
                    new
                         {
                             @class = "form-control",
                            autofocus = "autofocus"
                         })
                @Html.ValidationMessageFor(x => x.Invoice.Title)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Invoice.ClientId)
                @Html.DropDownListFor(x => x.Invoice.ClientId,
                    new SelectList(Model.Clients, "Id", "Name"),
                    "-- Wybierz klienta --",
                    new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Invoice.ClientId)
            </div>

            if (Model.Invoice.Id != 0)
            {
                <div class="form-group">
                    @Html.LabelFor(x => x.Invoice.Value)
                    @Html.TextBoxFor(x => x.Invoice.Value,
                        new { @class = "form-control", @readonly = "readonly" })
                </div>
            }

            <div class="form-group">
                @Html.LabelFor(x => x.Invoice.MethodOfPaymentId)
                @Html.DropDownListFor(x => x.Invoice.MethodOfPaymentId,
                    new SelectList(Model.MethodsOfPayment, "Id", "Name"),
                    "-- Wybierz sposób płatności --",
                    new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Invoice.MethodOfPaymentId)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Invoice.PaymentDate)
                @Html.TextBoxFor(x => x.Invoice.PaymentDate,
                    "{0:dd-MM-yyyy}",
                    new
                    {
                        @class = "form-control",
                        @id = "PaymentDate",
                        autocomplete = "off"
                    })
                @Html.ValidationMessageFor(x => x.Invoice.PaymentDate)
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Invoice.Comments)
                @Html.TextAreaFor(x => x.Invoice.Comments,
                    new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Invoice.Comments)
            </div>

            <button class="btn btn-primary btn-lg mb-5" type="submit">
                Zapisz
            </button>

        }
    </div>
    <div class="col-5 offset-lg-1">
        @if (Model.Invoice.Id != 0)
        {
            @Html.Partial("_InvoicePosition", Model.Invoice.InvoicePositions)
        }
    </div>
</div>


@section Scripts
{

    <script type="text/javascript">
        function generatePdf() {
            $.ajax({
                type: 'POST',
                url: "@Url.Action("InvoiceToPdf", "Print")",
                data: {
                    id: '@Model.Invoice.Id'
                },
                success: function (data) {
                    window.location = '@Url.Action("DownloadInvoicePdf", "Print")' + '?fileGuid=' + data.FileGuid + '&fileName=' + data.FileName;
                },
                error: function (data) {
                    alert(data.Message);
                },
                dataType: 'json',
                cache: false
            });
        }

        

        $(document).ready(function () {

            $.validator.methods.number = function (value, element) {
                return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
            };

            $.validator.methods.date = function (value, element) {
                var isChrome = /Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor);
                if (isChrome) {
                    var d = new Date();
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(d.toLocaleDateString(value)));
                } else {
                    return this.optional(element) || !/Invalid|NaN/.test(new Date(value));
                };
            };

            $('#PaymentDate').datepicker({
                format: "dd-mm-yyyy",
                language: "pl",
                multidate: false,
                autoclose: true,
                todayHighlight: true,
                forceParse: false
            });


        });

        function deleteInvoicePosition(id, invoiceId, btn) {
            if (!confirm("Czy na pewno chcesz usunąć pozycję?"))
                return;

            $.ajax({
                type: 'POST',
                url: "@Url.Action("DeletePosition", "Home")",
                data: {
                    id: id,
                    invoiceId: invoiceId
                },
                success: function (data) {
                    if (data.Success) {
                        var row = btn.parentNode.parentNode;
                        row.parentNode.removeChild(row);

                        $('#Invoice_Value').val(data.InvoiceValue.toFixed(2).replace(".", ","));
                    } else {
                        alert(data.Message);
                    }
                },
                error: function (data) {
                    alert(data.Message);
                },
                dataType: 'json'
            });
        }
    </script>
}

InvoiceManager/Views/Home/InvoicePosition.cshtml
@model InvoiceManager.Models.ViewModels.EditInvoicePositionViewModel
@{
    ViewBag.Title = Model.Heading;
}

<h1>@Model.Heading</h1>

@using (Html.BeginForm("InvoicePosition", "Home"))
{
    @Html.AntiForgeryToken()

    if (Model.InvoicePosition.Id == 0)
    {
        <p class="alert alert-info mt-4 mb-4">
            Pola lp, produkt oraz ilość są <strong>wymagane</strong>
        </p>
    }
    @Html.HiddenFor(x => x.InvoicePosition.Id)
    @Html.HiddenFor(x => x.InvoicePosition.InvoiceId)

    <div class="form-group">
        @Html.LabelFor(x => x.InvoicePosition.Lp)
        @Html.TextBoxFor(x => x.InvoicePosition.Lp,
            new
                 {
                     @class = "form-control",
                    autofocus = "autofocus"
                 })
        @Html.ValidationMessageFor(x => x.InvoicePosition.Lp)
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.InvoicePosition.ProductId)
        @Html.DropDownListFor(x => x.InvoicePosition.ProductId,
            new SelectList(Model.Products, "Id", "Name"),
            "-- Wybierz produkt --",
            new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.InvoicePosition.ProductId)
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.InvoicePosition.Quantity)
        @Html.TextBoxFor(x => x.InvoicePosition.Quantity,
            new
                 {
                     @class = "form-control"
                 })
        @Html.ValidationMessageFor(x => x.InvoicePosition.Quantity)
    </div>

    if (Model.InvoicePosition.Id != 0)
    {
        <div class="form-group">
            @Html.LabelFor(x => x.InvoicePosition.Value)
            @Html.TextBoxFor(x => x.InvoicePosition.Value,
                new { @class = "form-control", @readonly = "readonly" })
        </div>
    }

    <button class="btn btn-primary btn-lg mb-5" type="submit">
        Zapisz
    </button>

}

@section Scripts
{
    <script type="text/javascript">

        $(document).ready(function () {

            $.validator.methods.number = function (value, element) {
                return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
            };

        });

    </script>
}

InvoiceManager/Views/Home/_InvoicePosition.cshtml
@model IEnumerable<InvoiceManager.Models.Domains.InvoicePosition>

<div class="row">
    <h2>Pozycje faktury</h2>
    <table class="table table-hover table table-striped mt-3 mb-5">
        <thead>
            <tr>
                <th scope="col">Lp</th>
                <th scope="col">Produkt</th>
                <th scope="col">Ilość</th>
                <th scope="col">Wartość</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var position in Model)
            {
                <tr>
                    <td>
                        <a class="fw-bold text-decoration-none"
                           href="@Url.Action("InvoicePosition",
                                     "Home",
                                     new { invoiceId = position.InvoiceId, invoicePositionId = position.Id })">
                            @position.Lp
                        </a>
                    </td>
                    <td>@position.Product.Name</td>
                    <td>@position.Quantity</td>
                    <td>@position.Value zł </td>
                    <td>
                        <button class="btn btn-danger btn-sm"
                                onclick="deleteInvoicePosition('@position.Id', @position.InvoiceId, this)">
                            Usuń
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>